# 1. Base image from KP repo 
FROM docker-baseimages.devopsrepo.project.org/websphere-liberty: 21.0.0.8-full-javag-ibmjava-kp

# 2. Copy war file artifact into dropins inside container
COPY --chown=default:0 target/*.war /config/dropins/dmcservice.war

COPY --chown=default:0 war/src/main/resources/server.xml /config/

# 3. Default setting for the verbose option
ARG SSL=true 
ARG MP_MONITORING=true
ARG VERBOSE=false

# 4. Switching to non-root user 
USER default

#Run command to check the seccomp 
RUN grep Seccomp /proc/S$/status

# 5. Required for liberty 
RUN configure.sh

# 6. Add app label 
LABEL apps='dmcservice'

