steps:

- task: DownloadPipelineArtifact@2
  displayName: "Download Artifact"
  inputs:
    source: 'current'
    artifact: 'ApplicationArtifact'
    path: '$(Build.ArtifactStagingDirectory)'
    checkDownloadedFiles: true